### PR TITLE
Tweaked some colors for JS

### PR DESCRIPTION
**Pull request by mrenty**

### CODE REVIEW

**Comment by imcatnoone** [comment]
hey @mrenty! what exactly was changed? I can't view the file for some reason to see what was changed.

**Comment by mrenty** [comment]
Yeah file changes don't show because it's a `.jar` file, but it was a small color change when it was selected so it was more visible in a JavaScript syntax.

**Comment by timothyis** [comment]
I think it would be cool to see a screenshot of this. @mrenty

**Comment by imcatnoone** [comment]
@mrenty Yeah like @CodeTheory said, would love to see an image. If anything, may be cool to port over to the other IDE's.

**Pull request closed without merging**
