### PR TITLE
Atom Theme

### PR DESCRIPTION
**Pull request by timothyis**
Hey @imcatnoone. How's this?

Once this is merged I can publish this to the Atom Package Manager and then write install instructions via the README. 😄

### CODE REVIEW

**Comment by imcatnoone** [comment]
Hey @CodeTheory! I absolutely love it. Merging now. Can you point me toward the section of the code for the sidebar? Would adapt that color scheme for my sidebar as well. Haven't done that yet for Sublime.

**Comment by timothyis** [comment]
@imcatnoone I haven't touched the sidebar yet, but I think it falls under the `atom-panel` element. What specifically do you want done? I can have a go at doing it if you like. 😃

Also, you can open Atom in Dev mode by typing `atom --dev .` in a directory via the command line and then you can use the web inspector to mess around with the styling.

**Comment by imcatnoone** [comment]
@CodeTheory:
- Adding you to the README once this is good to go and the website as well. What name do you prefer on the website?
- Can you open a PR on the README for the install instructions and such once you have them?
- Ah okay! I want to change the sidebar of Sublime to match the color scheme of the theme itself. Right now it's the light version which obviously doesn't match. I like the colors you have there. Seems like BG is the same, and the folders are the pale blue.
- Were you able to install Toothpaste via the Package Control on Sublime? Seems like some folks were unable to. Trying to figure out why that's the case since it works for me.

:+1: Thanks a ton! You're kick ass.

**Comment by timothyis** [comment]
@imcatnoone 

It looks like I can't actually publish to APM because I'm not part of this repository. You can publish to APM if you have atom installed by going to the atom toothpaste theme directory and typing `apm publish` and then we can write install instructions on the Readme.
1. I'd prefer just 'Timothy' if my name is used anywhere.
2. Ah, I don't actually know about editing Sublime, unfortunately. I just copied all of your colour variables and applied them to Atom. 
3. As a consequence of above and not installing Sublime, I haven't installed the Toothpaste sublime package. Very sorry! 

Thank you! This is an incredibly beautiful theme and I'm glad I was able to contribute to something that's going to make working a lot easier for me and others!

**Comment by imcatnoone** [comment]
@CodeTheory - Oh! I'll have to install Atom then and publish it to APM. No problem. Stepping away from my computer for a bit and will do it afterward. If I run into hiccups, I'll ping you.

And no problem regarding everything else :) Super happy to have you contributing. So awesome. The theme for Atom looks beautiful!

**Pull request merged**
